#This macro, which includes all the commands to set the geometry reported
#also in rum.mac, is automatically called when running OREOfs in interactive mode. 
#It can therefore be used to check the correctness of the set parameters.

#/random/setSeeds 19577793 424238335        #uncomment this to have reproducibility

#geometry
/crystal/setDetectorVersion 1               #0 for single crystal, 1 is oreo
/crystal/nCrystalsX 5                       #max 7
/crystal/nCrystalsY 6                      
/crystal/setCrystalMaterial W               #W, PWO
/crystal/setCrystalSize 25 25 25 mm
/crystal/setCrystalLattice <111>            #planes (e.g. (111)) or axes (e.g. <111>)
/crystal/setCrystalAngleX 0.e-6             #rad (default 0.)
/crystal/setCrystalAngleY 0.e-6             #rad (default 0.)
#/crystal/setGap 1.0 mm                      #defualt 0.1 mm
#/crystal/setOCeffects false                 #default is true
#/crystal/setChannelingDataPath potentialPath/

#/crystal/setVirtualDetectorSize 40 40 0.001 cm
