/run/numberOfThreads 2

/random/setSeeds 19577793 424238335        #uncomment this to have reproducibility

#geometry
/crystal/setDetectorVersion 1               #0 for single crystal, 1 is oreo
/crystal/nCrystalsX 1                       #max 7
/crystal/nCrystalsY 1
/crystal/setCrystalMaterial PWO             #W, PWO
/crystal/setCrystalSize 25 25 45 mm
/crystal/setCrystalLattice <100>            #planes (e.g. (111)) or axes (e.g. <111>)
/crystal/setCrystalAngleX 0.e-6             #rad (default 0.)
/crystal/setCrystalAngleY 0.e-6             #rad (default 0.)
/crystal/setOCeffects true                  #default is true
/crystal/setChannelingDataPath ../potentialPath/

#/crystal/setVirtualDetectorSize 40 40 0.001 cm

#physics and run options
/phys/setCoherentPairProduction

/run/setfilenamesave output/output_axial_50GeV.root
#/run/setfilenamesave output/output_random_50GeV.root

/run/initialize

/control/verbose 0
/run/verbose 1                              #to see the Couples CutsVsRegion
/tracking/verbose 0

#beam
/gps/particle e-
#coordinate distribution
/gps/pos/centre 0 0 -30 mm
/gps/pos/type Beam
/gps/pos/sigma_x 1.0 mm
/gps/pos/sigma_y 1.0 mm
#angular distribution
/gps/ang/type beam2d
/gps/ang/rot1 1  0  0
/gps/ang/rot2 0 -1  0
/gps/ang/sigma_x 1.E-6 rad
/gps/ang/sigma_y 1.E-6 rad
#energy distribution
/gps/ene/mono 50 GeV

#mesh scorer
/score/create/boxMesh boxMesh1
/score/mesh/boxSize 37.5 37.5 22.5 mm       #semi-quantities
/score/mesh/nBin 75 75 45
/score/mesh/translate/xyz 0 0 -22.5 mm
/score/quantity/energyDeposit Edep GeV      #[GeV]
/score/close
/score/list

#statistics
/run/printProgress 10
/run/beamOn 100

#write boxMesh scorer reults to file
#/score/dumpQuantityToFile boxMesh1 Edep output/Edep_axial_50GeV.txt
#/score/dumpQuantityToFile boxMesh1 Edep output/Edep_random_50GeV.txt

