/run/numberOfThreads 2

/random/setSeeds 19577793 424238335        #uncomment this to have reproducibility

#Radiator Crystal settings

#/crystal/setCrystalSize 20 20 2 mm
#/crystal/setCrystalLattice <100>           #planes (e.g. (111)) or axes (e.g. <111>)
/crystal/setCrystalAngleX 0.e-6             #rad (default 0.)
/crystal/setCrystalAngleY 0.e-6             #rad (default 0.)
/crystal/setDetectorVersion 1               #0 for single crystal #1 is oreo
/crystal/setOCeffects false                 ######(de)comment coherentpairproduction!!!
/run/initialize
/run/setfilenamesave output/rnd.root

#/crystal/setVirtualDetectorSize 40 40 0.001 cm

#further settings
#/det/setScoringCrystalExit true             #score all particles exiting the radiator crystal


/control/verbose 0
/run/verbose 0                              #to see the Couples CutsVsRegion
/tracking/verbose 0

#beam
/gun/UseGPS true
/gps/particle e-
#coordinate distribution
/gps/pos/centre 0 0 -30 mm
/gps/pos/type Beam
/gps/pos/sigma_x 1.0 mm                    
/gps/pos/sigma_y 1.0 mm                 
#angular distribution
/gps/ang/type beam2d
/gps/ang/rot1 1  0  0
/gps/ang/rot2 0 -1  0
/gps/ang/sigma_x 1.E-6 rad
/gps/ang/sigma_y 1.E-6 rad
#energy distribution
/gps/ene/mono 50 GeV

/score/create/boxMesh boxMesh1                
/score/mesh/boxSize 50 50 4.0 mm            #semi-quantities
/score/mesh/nBin 401 401 33                
/score/mesh/translate/xyz 0 0 504.03 mm     #CHECK ALWAYS!
/score/quantity/energyDeposit Edep          #[MeV]       
/score/close
/score/list

/score/create/boxMesh boxMesh2                
/score/mesh/boxSize 10 10 1.0 mm            #semi-quantities
/score/mesh/nBin 81 81 9                
/score/mesh/translate/xyz 0 0 -1.0 mm
/score/quantity/energyDeposit Edep          #[MeV]        
/score/close
/score/list                

#statistics
/run/printProgress 0
/run/beamOn 200
